  const list = [
    {
      id: 1,
      pName: "OnePlus",
      pRam: "128GB",
      simType: "Single SIM - 5G",
      prating: 4.8,
      price: 19.99900,
      type: "Free delivery",
      img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSm8AsTxa7l5PK0iV1EIx9lga7o7F3hyOi0es_HWQv2qC2fV2mRGluaOg9Fv5kL52XHKCjOcxIpBi5wTDHo_9VOovXikQN0rxYpsasMsLlO_Btu0s2WcRtGNQ&usqp=CAE",
      star: "⭐⭐⭐⭐⭐",
      amount: 1,
    },
    {
      id: 2,
      pName: "OPPO Reno 4 PRO ",
      pRam: "128GB",
      simType: "Dual SIM - 4G",
      prating: 3.4,
      price: 24.99900,
      type: "Free delivery",
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTM8ZLszTPVPyhCq0Rjw8qjztVHX4XlOWQe2rKppCWwdPGewG5PQ5fVlXwgSrB43NTj7Xb5SGjzIrbjeMCkmaEprpSEPgPBYfS6E40tIvNI8iLs-TymIzb0ew&usqp=CAE",
      star: "⭐⭐⭐",
      amount: 1,
    },
    {
      id: 3,
    pName: "VIVO V23e",
      pRam: "128GB",
      simType: "Single SIM - 5G",
      prating: 3.1,
      price: 25.99900,
      type: "Free delivery",
      img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQgdeGRZMtKq3UiKCIaig0lkAbhzfSdG7OXLII-CHltPp6PETD3Yb3mjBBrDyyxMZWilRVuKV6LhGf-XohY0k17lHkzxSxjGwCJxq3m11LBogPEJcs4sIYTOA&usqp=CAE",
      star: "⭐⭐⭐",
      amount: 1,
    },
    {
      id: 4,
      pName: "LAVA",
      pRam: "256GB",
      simType: "Single SIM - 5G",
      prating: 4.2,
      price: 19.99900,
      type: "Free delivery",
      img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR0JZ1DB0EvEN31KdpqK_pz57RpWlm6_EWNwtuMLeXenKATYs2G7y8UWRszi3jrjjhbpjiBBHDj9BFlExceO5SyRbiSyXkhfRXTMj_qcTg4buJCPvcTnaxi_g&usqp=CAE",
      star: "⭐⭐⭐⭐",
      amount: 1,
    },
    {
      id: 5,
      pName: "Redmi A2 ",
      pRam: "64GB",
      simType: "Dual SIM - 4G",
      prating: 2.2,
      price: 6.79900,
      type: "Free delivery",
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS2_COiz3FrGEG9xb7IJn-8DdWdpkCcAo_VC3g5rWa6jwAg_oZMKq6lyIekkFXhq4HnPXkdM9BW8X1DBQh663IqJ_AUAojT_kv9bmY0LXjFTxDjypy5Ac3F&usqp=CAE",
      star: "⭐⭐",  
      amount: 1,
    },
    {
      id: 6,
      pName: "TECNO Pova 5",
      pRam: "128GB",
      simType: "Single SIM - 5G",
      prating: 3.4,
      price: 12.99900,
      type: "Free delivery",
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTWGldW5OPDVI0GX83e3IBU0IyXM3cnvPb04OBFzuOUQCmTAS5G1HFPBNh_CNZOM0lHflT3YO5cQztOY45YM9FkGzdVwKUzoNZU0dtTWRnub-qACSK3bhsvag&usqp=CAE",
      star: "⭐⭐⭐",
      amount: 1,
    },
    {
      id: 7,
      pName: "Samsung Galaxy ",
      pRam: "64GB",
      simType: "Dual SIM - 4G",
      prating: 1.7,
      price: 9.49900,
      type: "Free delivery",
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRzZXz9pwo7TeJUZexJCdD1rdc6qJzm9NiuPFFzExx6VuAmjlmSowT1EVVDK4bDQQkNzE5q5-5li08CqoKz5CyqjW1VMYdGjDziUJFaRDwYsmn0vsy3F70TzQ&usqp=CAE",
      star: "⭐",
      amount: 1,
    },
    {
      id: 8,
      pName: "Infinix Hot 30 5G",
      pRam: "128GB",
      simType: "Single SIM - 5G",
      prating: 3.2,
      price: 16.999,
      type: "Free delivery",
      img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSZ7vnlq22HK8kl_Bi-UMQhMnSCsWOZSEw1_Ij0Iu5XrqVTmUnRWrdx47Vra4GFouGTM0nDOdcMO6447yirfM2NaDBPIWBxxYUPyFNmuqeXJRPWmJzVtNae_Q&usqp=CAE",
      star: "⭐⭐⭐",
      amount: 1,
    },
    {
      id: 9,
      pName: "OnePlus Nord CE 5G",
      pRam: "256GB",
      simType: "Dual SIM - 4G",
      prating: 4.8,
      price: 27.99900,
      type: "Free delivery",
      img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRnFoIYmYZhs2r9mtG-2JbbYieJGjGKTZ0UDxOghjrkMqyF4_kuiKcKbHMPBQbfLYSAEfjbGyHM3xIlaAwduNGFHG24MmnhrTs6HOCp3yYDbGC0l7H03WF1rw&usqp=CAE",
      star: "⭐⭐⭐⭐⭐",
      amount: 1,
    },
    {
      id: 10,
      pName: "Apple iPhone",
      pRam: "128GB",
      simType: "Single SIM",
      prating: 4.8,
      price: 25.99900,
      type: "Free delivery",
      img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTqX3kBP7Fcv9R-1M5FvBTUEHl13XL8jrWHQSIgaQEkj6cg1fZbo1Byals1voVVwRxt5yPmhevUPLOaalNmQjF-d5kq9Hh_zA63xtR-dsdxAsKBQSEub-js&usqp=CAE",
      star: "⭐⭐⭐⭐⭐",
      amount: 1,
    },
    {
      id: 11,
      pName: "Jio Phone Next",
      pRam: "32GB",
      simType: "Dual SIM - 4G",
      prating: 1.4,
      price: 5.7990,
      type: "Free delivery",
      img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT5ESPE_QTYcEfdXZ5p1XkeN7gUHL1qhDQEgMIlKsX_BlV39TfwzDqfTJ3FXhpChWhnxYDziQ2Rn1tJXUokndXBB28CFDZPaBq87Wns3oPAxKs2B-XdWEgK0w&usqp=CAE",
      star: "⭐",
      amount: 1,
    },
    {
      id: 12,
      pName: "REALME 10 8GB",
      pRam: "128GB",
      simType: "Single SIM - 4G",
      prating: 3.8,
      price: 19.99900,
      type: "Free delivery",
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTNPSBU1DvNflaX6wnGYFqKj0T-K2QWetGmGWyXvui-aDz7yULxqg66NEjFEGs51sX7M18qEd3Zwc_ecG4P8_2x3gxI45iY5u0R7JloNz9Cohu0YSPcX-5ESw&usqp=CAE",
      star: "⭐⭐⭐",
      amount: 1,
    },
  ];

  export default list;
